--Total Revenue generated by each product
Select p.Product_Name, Sum(s.Quantity * p.[Unit_Cost_USD]) As Total_Revenue_From_Product
From Sales s
Join Products p On s.ProductKey = p.ProductKey
Group By p.Product_Name

--Total Revenue generated by each category
Select p.Category, Sum(s.Quantity * p.[Unit_Price_USD]) As Total_Revenue_Each_Category
From Sales s
Join Products p On s.ProductKey = p.ProductKey
Group By p.Category

--Total revenue generated by each store
Select sk.StoreKey, SUM(s.Quantity * p.[Unit_Price_USD]) AS Total_Revenue_Each_Store
From Sales s
Join Products p On s.ProductKey = p.ProductKey
Join Stores sk On s.StoreKey = sk.StoreKey
Group By sk.StoreKey

--Top selling products (by quantity) in each Category
SELECT p.Category, p.Product_Name, SUM(s.quantity) AS Total_Quantity_Sold
FROM Sales s
JOIN Products p ON s.ProductKey = p.ProductKey
GROUP BY p.Category, p.Product_Name
ORDER BY Total_Quantity_Sold DESC

--Total revenue generated by each state
SELECT st.State, SUM(s.quantity * p.[Unit_Price_USD]) AS Revenue_From_Each_State
FROM Sales s
JOIN Products p ON s.productkey = p.productkey
JOIN Stores st ON s.storekey = st.StoreKey
GROUP BY st.State

--Number of orders per month
SELECT YEAR(s.orderdate) AS Year, MONTH(s.orderdate) AS Month, COUNT(s.ordernumber) AS Number_of_Orders
FROM Sales s
GROUP BY YEAR(s.orderdate), MONTH(s.orderdate)
ORDER BY year, month

--Total revenue generated by each product brand
SELECT p.Brand, SUM(s.quantity * p.[Unit_Price_USD]) AS Brand_Revenue
FROM Sales s
JOIN Products p ON s.productkey = p.productkey
GROUP BY p.Brand